# Deep Learning: Laboratory Tasks Compilation
**Course:** DS413 | Deep Learning  
**Student:** Kent John Ugsimar Macalam  
**Program:** Bachelor of Science in Data Science (USTP)  
---
### Table of Contents
1. [Laboratory Task 1: Four Types of Data Analytics](#laboratory-task-1)
2. [Lecture Task 1: Reaction Paper - WIRED Film: Living in the Age of AI](#lecture-task-1)
3. [Laboratory Task 2: ANN Forward Pass & Error Calculation](#laboratory-task-2)
4. [Laboratory Task 3: Forward and Backward Propagation (NumPy)](#laboratory-task-3)
5. [Laboratory Task 4: 2-Layer Linear Regression in PyTorch](#laboratory-task-4)
6. [Laboratory Task 5: PyTorch Tensor Operations and Manipulation](#laboratory-task-5)
---

## Laboratory Task 1

<div class="alert alert-block alert-success" style="font-family: Times New Roman">
    <h4><strong>Laboratory Task 1</strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
    <b>Instruction:</b> From the example scenario above, create additional two inquiries for each type of data analytics.
</p>

<ol>
    <li><b>Descriptive:</b></li>
    <li><b>Diagnostic:</b></li>
    <li><b>Predictive:</b></li>
    <li><b>Prescriptive:</b></li>
</ol>
</div>

### Solution & Inquiries

**Scenario Context:** Dr. Jake is a medical doctor and the CEO of Astro JR, a pharmaceutical company in the Philippines producing and deploying the COVID-19 vaccine worldwide.

#### 1. Descriptive Analytics
*Focus: Summarizing historical records to capture what happened.*
- **Inquiry 1:** What was the total number of AstroJR vaccine doses distributed and administered across each administrative region of the Philippines over the past quarter?
- **Inquiry 2:** What percentage of vaccinated individuals reported mild or moderate adverse reactions within 48 hours of vaccination across clinical batches?

#### 2. Diagnostic Analytics
*Focus: Investigating underlying root causes and correlations to explain why events occurred.*
- **Inquiry 1:** Why did vaccine uptake and demand drop significantly in specific rural provinces during the second quarter?
- **Inquiry 2:** Which supply chain disruptions (e.g., cold-chain temperature deviations, transit delays) were the primary causes of vaccine dose spoilage during distribution?

#### 3. Predictive Analytics
*Focus: Leveraging statistical and machine learning models to project future outcomes.*
- **Inquiry 1:** What will be the projected global demand for AstroJR booster doses over the next six months based on emerging variant transmission rates?
- **Inquiry 2:** Which geographic areas have the highest probability of experiencing a COVID-19 case surge in the upcoming month?

#### 4. Prescriptive Analytics
*Focus: Recommending optimal courses of action and resource allocations given operational constraints.*
- **Inquiry 1:** How should AstroJR reallocate its cold-storage transport fleet across distribution hubs to minimize delivery times and eliminate vaccine wastage during regional spikes?
- **Inquiry 2:** What is the optimal production schedule and raw material procurement strategy needed to meet anticipated demand surges without exceeding warehouse holding limits?

---
## Lecture Task 1

<div class="alert alert-block alert-success" style="font-family: Times New Roman">
    <h4><strong>Lecture Task 1</strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
    <b>Instruction:</b> Create a reaction paper (1 page) about the YouTube video titled "Machine Learning: Living in the Age of AI | A WIRED Film".
</p>

<center><a href="https://youtu.be/ZJixNvx9BAc"><img class="thumbnail" src="https://i.ytimg.com/vi/ZJixNvx9BAc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC2BCMXLS08rsO8o1LJzpXMjxOP9A" alt="YouTube Thumbnail" width="300px"></a></center>

<p>
    Use these as guide question for your paper.
</p>
<ul>
    <li>What are some of the most significant advancements in AI that the video highlights as having a positive impact on society?</li>
    <li>How does the video envision the future of AI, and what challenges and opportunities lie ahead?</li>
    <li>How can we strike a balance between harnessing the benefits of AI and addressing its potential drawbacks?</li>
</ul>
</div>

### Reaction Paper

**Video Reference:** [WIRED Film - Living in the Age of AI](https://youtu.be/ZJixNvx9BAc)

#### 1. Significant Advancements and Positive Societal Impacts
The documentary demonstrates how machine learning has evolved from an abstract scientific field into a practical driver of human progress:
- **Medical Diagnostics & Oncology:** Deep convolutional neural networks analyze high-dimensional clinical data with remarkable accuracy. Stanford researchers trained a model on over 120,000 dermatological images capable of diagnosing malignant skin lesions on par with board-certified dermatologists. Additionally, student innovator Rishab Jain developed an AI segmentation tool for 3D abdominal scans to localize the pancreas, enabling targeted radiotherapy while sparing surrounding organs.
- **Smart Agriculture & Food Systems:** Faced with labor shortages and escalating global food demands, farmers deploy computer vision and autonomous robotics for precision weed eradication, crop hydration management, and yield forecasting, reducing pesticide dependency while boosting yields.
- **Democratization of Technology:** Open-source ecosystems allow independent developers—such as the DIY Robo Cars community—to deploy autonomous driving algorithms using cloud computing and consumer hardware.

#### 2. Future Vision, Opportunities, and Challenges
The film envisions an era where machine learning automates routine cognitive and manual tasks, echoing the economic transformations of the Industrial Revolution. Autonomous vehicles promise safer roadways and optimized transit logistics.

However, this rapid transformation brings serious challenges:
- **Labor Market Displacement:** The speed of algorithmic automation threatens rapid obsolescence for routine clerical and physical vocations before workers can retrain.
- **Information Integrity & Synthetic Media:** Deepfake technology and real-time facial manipulation present severe risks for political disinformation, fraud, and identity impersonation.
- **Algorithmic Bias & Pervasive Surveillance:** Unregulated facial recognition and predictive scoring risk entrenching systemic discrimination and eroding civil liberties.

#### 3. Striking an Equilibrium
To harness the benefits of artificial intelligence while mitigating its risks, a balanced governance framework is required:
- **Ethical Regulation & Provenance Verification:** Enacting enforceable standards for biometric data privacy, transparency in predictive algorithms, and cryptographic verification for synthetic media.
- **Curriculum Modernization:** Modernizing education toward multidisciplinary problem solving, data literacy, and continuous technical retraining.
- **Human-in-the-Loop Safeguards:** Ensuring automated systems in high-stakes domains (healthcare, criminal justice, public administration) retain human moral agency and accountability.

---
## Laboratory Task 2

<div class="alert alert-block alert-success" style="font-family: Times New Roman">
    <h4><strong>Laboratory Task 2</strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
    <b>Instruction:</b> Perform a single forward pass and compute for the error.
</p>

$$x = \begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix}, \quad y = \begin{bmatrix} 1 \end{bmatrix}, \quad f(Z_n) = \max(0, Z_n)$$

$$\text{hidden unit weights } W_h = \begin{bmatrix} w_{11}=0.2 & w_{12}=-0.3 \\ w_{13}=0.4 & w_{14}=0.1 \\ w_{15}=-0.5 & w_{16}=0.2 \end{bmatrix}$$

$$\text{output unit weights } W_o = \begin{bmatrix} w_{21}=-0.3 \\ w_{22}=-0.2 \end{bmatrix}, \quad \theta = \begin{bmatrix} \theta_1 = -0.4 \\ \theta_2 = 0.2 \\ \theta_3 = 0.1 \end{bmatrix}$$
</div>

### Step-by-Step Analytical Derivation

#### 1. Hidden Layer Net Inputs ($Z_1, Z_2$)
$$\begin{aligned} Z_1 &= w_{11}x_1 + w_{13}x_2 + w_{15}x_3 + \theta_1 \\     &= (0.2)(1) + (0.4)(0) + (-0.5)(1) + (-0.4) \\     &= 0.2 + 0 - 0.5 - 0.4 = \mathbf{-0.7} \\ Z_2 &= w_{12}x_1 + w_{14}x_2 + w_{16}x_3 + \theta_2 \\     &= (-0.3)(1) + (0.1)(0) + (0.2)(1) + (0.2) \\     &= -0.3 + 0 + 0.2 + 0.2 = \mathbf{0.1} \end{aligned}$$

#### 2. Hidden Layer Activations ($H_1, H_2$)
Applying the ReLU activation function $f(Z) = \max(0, Z)$:
$$\begin{aligned} H_1 &= \max(0, Z_1) = \max(0, -0.7) = \mathbf{0.0} \\ H_2 &= \max(0, Z_2) = \max(0, 0.1) = \mathbf{0.1} \end{aligned}$$

#### 3. Output Layer Net Input ($Z_3$)
$$\begin{aligned} Z_3 &= w_{21}H_1 + w_{22}H_2 + \theta_3 \\     &= (-0.3)(0.0) + (-0.2)(0.1) + 0.1 \\     &= 0.0 - 0.02 + 0.1 = \mathbf{0.08} \end{aligned}$$

#### 4. Predicted Output ($\hat{y}$)
$$\hat{y} = \max(0, Z_3) = \max(0, 0.08) = \mathbf{0.08}$$

#### 5. Error Computations
- **Residual / Output Error ($\delta$):**
  $$\delta = \hat{y} - y = 0.08 - 1.0 = \mathbf{-0.92}$$
- **Squared Error ($E$):**
  $$E = \frac{1}{2}(\hat{y} - y)^2 = \frac{1}{2}(-0.92)^2 = \frac{1}{2}(0.8464) = \mathbf{0.4232}$$
- **Mean Squared Error (MSE):**
  $$\text{MSE} = (\hat{y} - y)^2 = (-0.92)^2 = \mathbf{0.8464}$$

---
## Laboratory Task 3

<div class="alert alert-block alert-success" style="font-family: Times New Roman">
    <h4><strong>Laboratory Task 3</strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
    <b>Instruction:</b> Perform a forward and backward propagation in python using the inputs from <b>Laboratory Task 2</b>
</p>

```python
x = np.array()
y = np.array()

# use relu as the activation function.

# learning rate
lr = 0.001

```
</div>

### Code Implementation

In [1]:
import numpy as np

# 1. Define Input and Target from Laboratory Task 2
x = np.array([[1.0, 0.0, 1.0]])  # Shape: (1, 3)
y = np.array([[1.0]])             # Shape: (1, 1)

# 2. Initialize Weights and Biases from Laboratory Task 2
W_h = np.array([
    [ 0.2, -0.3],
    [ 0.4,  0.1],
    [-0.5,  0.2]
])                                # Shape: (3, 2)
b_h = np.array([[-0.4, 0.2]])     # Biases theta1, theta2 (1, 2)

W_o = np.array([
    [-0.3],
    [-0.2]
])                                # Shape: (2, 1)
b_o = np.array([[0.1]])           # Bias theta3 (1, 1)

lr = 0.001                        # Learning rate alpha

# 3. Activation Functions
def relu(z):
    return np.maximum(0, z)

def relu_derivative(z):
    return (z > 0).astype(float)

# ----------------- FORWARD PROPAGATION -----------------
Z_h = np.dot(x, W_h) + b_h
H = relu(Z_h)

Z_o = np.dot(H, W_o) + b_o
y_hat = relu(Z_o)

loss = 0.5 * np.sum((y_hat - y) ** 2)

print("=== FORWARD PROPAGATION RESULTS ===")
print(f"Z_h (Hidden Pre-activation): {Z_h}")
print(f"H   (Hidden Activation):     {H}")
print(f"Z_o (Output Pre-activation): {Z_o}")
print(f"y_hat (Model Prediction):    {y_hat}")
print(f"Initial Loss:                {loss:.6f}\n")

# ----------------- BACKWARD PROPAGATION -----------------
delta_o = (y_hat - y) * relu_derivative(Z_o)
delta_h = np.dot(delta_o, W_o.T) * relu_derivative(Z_h)

dW_o = np.dot(H.T, delta_o)
db_o = delta_o

dW_h = np.dot(x.T, delta_h)
db_h = delta_h

# Gradient Descent Updates
W_o_updated = W_o - lr * dW_o
b_o_updated = b_o - lr * db_o
W_h_updated = W_h - lr * dW_h
b_h_updated = b_h - lr * db_h

print("=== BACKWARD PROPAGATION GRADIENTS ===")
print("dW_o:\n", dW_o)
print("db_o:\n", db_o)
print("dW_h:\n", dW_h)
print("db_h:\n", db_h)

print("\n=== UPDATED PARAMETERS (lr = 0.001) ===")
print("Updated W_o:\n", W_o_updated)
print("Updated b_o:\n", b_o_updated)
print("Updated W_h:\n", W_h_updated)
print("Updated b_h:\n", b_h_updated)

=== FORWARD PROPAGATION RESULTS ===
Z_h (Hidden Pre-activation): [[-0.7  0.1]]
H   (Hidden Activation):     [[0.  0.1]]
Z_o (Output Pre-activation): [[0.08]]
y_hat (Model Prediction):    [[0.08]]
Initial Loss:                0.423200

=== BACKWARD PROPAGATION GRADIENTS ===
dW_o:
 [[ 0.   ]
 [-0.092]]
db_o:
 [[-0.92]]
dW_h:
 [[0.    0.184]
 [0.    0.   ]
 [0.    0.184]]
db_h:
 [[0.    0.184]]

=== UPDATED PARAMETERS (lr = 0.001) ===
Updated W_o:
 [[-0.3     ]
 [-0.199908]]
Updated b_o:
 [[0.10092]]
Updated W_h:
 [[ 0.2      -0.300184]
 [ 0.4       0.1     ]
 [-0.5       0.199816]]
Updated b_h:
 [[-0.4       0.199816]]


---
## Laboratory Task 4

<div class="alert alert-block alert-success" style="font-family: Times New Roman">
    <h4><strong>Laboratory Task 4</strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
    <b>Instruction:</b> Train a linear regression model in PyTorch using a regression dataset. Use the following parameters.
</p>

<ul>
    <li>Criterion: MSE Loss</li>
    <li>Fully Connected Layers x 2</li>
    <li>Batch Size: 8</li>
    <li>Optimizer: SGD</li>
    <li>Epoch: 1000</li>
</ul>
</div>

### Code Implementation

In [2]:
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader

# Set seed for reproducible results
torch.manual_seed(42)

# 1. Generate Synthetic Regression Dataset (128 samples, 3 input features, 1 target)
X = torch.randn(128, 3)
y = (2.0 * X[:, 0] - 3.0 * X[:, 1] + 1.5 * X[:, 2] + 0.5).unsqueeze(1) + 0.05 * torch.randn(128, 1)

# 2. Setup DataLoader with specified Batch Size = 8
batch_size = 8
dataset = TensorDataset(X, y)
train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

# 3. Construct Model with 2 Fully Connected Layers
class TwoLayerRegression(nn.Module):
    def __init__(self, in_features=3, hidden_features=16, out_features=1):
        super(TwoLayerRegression, self).__init__()
        self.fc1 = nn.Linear(in_features, hidden_features)   # Layer 1
        self.fc2 = nn.Linear(hidden_features, out_features)  # Layer 2
        
    def forward(self, x):
        out = self.fc1(x)
        out = self.fc2(out)
        return out

model = TwoLayerRegression(in_features=3, hidden_features=16, out_features=1)

# 4. Set Loss Criterion (MSE Loss) and Optimizer (SGD)
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# 5. Train for 1000 Epochs
epochs = 1000

print("=== BEGINNING TRAINING (1000 EPOCHS, BATCH SIZE 8) ===")
for epoch in range(epochs):
    epoch_loss = 0.0
    for batch_x, batch_y in train_loader:
        # Forward pass
        preds = model(batch_x)
        loss = criterion(preds, batch_y)
        
        # Backward pass & optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        epoch_loss += loss.item() * batch_x.size(0)
        
    epoch_loss /= len(dataset)
    
    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch + 1:4d}/{epochs}], Loss: {epoch_loss:.6f}")

print(f"\nTraining Complete! Final Epoch Loss: {epoch_loss:.6f}")

=== BEGINNING TRAINING (1000 EPOCHS, BATCH SIZE 8) ===
Epoch [ 100/1000], Loss: 0.002174
Epoch [ 200/1000], Loss: 0.002158
Epoch [ 300/1000], Loss: 0.002184
Epoch [ 400/1000], Loss: 0.002166
Epoch [ 500/1000], Loss: 0.002167
Epoch [ 600/1000], Loss: 0.002170
Epoch [ 700/1000], Loss: 0.002166
Epoch [ 800/1000], Loss: 0.002141
Epoch [ 900/1000], Loss: 0.002136
Epoch [1000/1000], Loss: 0.002187

Training Complete! Final Epoch Loss: 0.002187


---
## Laboratory Task 5

<div class="alert alert-block alert-success" style="font-family: Times New Roman">
    <h4><strong>Laboratory Task 5</strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
    <b>Instructions & Prompts:</b>
</p>

<ol>
    <li>Perform Standard Imports</li>
    <li>Create a function called <code>set_seed()</code> that accepts <code>seed: int</code> as a parameter, this function must return nothing but just set the seed to a certain value.</li>
    <li>Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the <code>set_seed()</code> function and use <code>42</code> as the seed parameter.</li>
    <li>Create a tensor "x" from the array above</li>
    <li>Change the dtype of x from <code>int32</code> to <code>int64</code></li>
    <li>Reshape <code>x</code> into a 3x2 tensor</li>
    <li>Return the right-hand column of tensor <code>x</code></li>
    <li>Without changing x, return a tensor of square values of <code>x</code></li>
    <li>Create a tensor <code>y</code> with the same number of elements as <code>x</code>, that can be matrix-multiplied with <code>x</code> (seed 42)</li>
    <li>Find the matrix product of <code>x</code> and <code>y</code>.</li>
</ol>
</div>

### Code Implementation

In [3]:
# 1. Perform Standard Imports
import torch
import numpy as np

# 2. Create set_seed() function
def set_seed(seed: int):
    np.random.seed(seed)
    torch.manual_seed(seed)

# 3. Create a NumPy array 'arr' of 6 random integers between 0 and 5
set_seed(42)
arr = np.random.randint(0, 5, 6)
print("3. NumPy array 'arr':", arr)

# 4. Create tensor x from array
x = torch.from_numpy(arr)
print("4. Tensor x:", x)

# 5. Change dtype of x from int32 to int64
print("5. Old Type:", x.type())
x = x.type(torch.int64)
print("   New Type:", x.type())

# 6. Reshape x into a 3x2 tensor
x = x.reshape(3, 2)
print("6. Reshaped x (3x2):\n", x)

# 7. Return the right-hand column of tensor x
print("7. Right-hand column:\n", x[:, 1:])

# 8. Without changing x, return a tensor of square values of x
x_squared = x.pow(2)
print("8. Squared values:\n", x_squared)
print("   Original x unchanged:\n", x)

# 9. Create tensor y with shape (2, 3) to permit matrix multiplication with x (3, 2)
set_seed(42)
y = torch.randint(0, 5, (2, 3))
print("9. Tensor y (2x3):\n", y)

# 10. Find the matrix product of x and y.
prod = torch.mm(x, y)
print("10. Matrix product prod (3x3):\n", prod)

3. NumPy array 'arr': [3 4 2 4 4 1]
4. Tensor x: tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)
5. Old Type: torch.IntTensor
   New Type: torch.LongTensor
6. Reshaped x (3x2):
 tensor([[3, 4],
        [2, 4],
        [4, 1]])
7. Right-hand column:
 tensor([[4],
        [4],
        [1]])
8. Squared values:
 tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])
   Original x unchanged:
 tensor([[3, 4],
        [2, 4],
        [4, 1]])
9. Tensor y (2x3):
 tensor([[2, 2, 1],
        [4, 1, 0]])
10. Matrix product prod (3x3):
 tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
